export * from './DetailPage'
export * from './components/EvolutionBase'
export * from './components/Heading'
export * from './components/Specifics'
export * from './components/Stats'
export * from './components/NavigationBtnMobile'